### PR TITLE
Fix plat exploits

### LINKED ISSUE #6002: White Metal Dust grants extra platinum
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Not get extra platinum
#
#### What happened instead? (Attach screenshots if needed)
whitemetalmixer
whitemetalcentrifuge
The platinum metallic powder can turn into more than 2 pure plat dust, especially when the plat line is processed using gt++ sifter for extra return.
#
#### What do you suggest instead/what changes do you propose?
Either make centrifuging white metal give you the 2 pure plat back or just 2 plat metallic powder

### PR DESCRIPTION
**Pull request by chochem**
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6002

White metal and helicopter need the same blacklisting as other alloys like EnderiumBase or HSSS to not result in unwanted (positive) loops.

tested in full pack and works:
image
image

### CODE REVIEW

**Review by NotAPenguin0 — APPROVED** [review]

File: src/main/java/com/github/bartimaeusnek/bartworks/system/material/GT_Enhancement/PlatinumSludgeOverHaul.java [hunk 1]
```diff
@@ -940,6 +940,12 @@ private static boolean isInBlackList(ItemStack stack) {
             } catch (ClassNotFoundException e) {
                 e.printStackTrace();
             }
+            if (stack.getItem() == GT_ModHandler.getModItem(GTPlusPlus.ID, "itemDustHeLiCoPtEr>", 1L).getItem()) {
+                return true;
+            }
+            if (stack.getItem() == GT_ModHandler.getModItem(GTPlusPlus.ID, "itemDustWhiteMetal>", 1L).getItem()) {
```
Comment (HoleFish) [inline src/main/java/com/github/bartimaeusnek/bartworks/system/material/GT_Enhancement/PlatinumSludgeOverHaul.java]: ~~`>`?~~ sorry

Comment (chochem) [reply src/main/java/com/github/bartimaeusnek/bartworks/system/material/GT_Enhancement/PlatinumSludgeOverHaul.java]: was from copy pasting mt hand. but yea I already fixed that myself :P
