### PR TITLE
Fix multiblock structure check bugs related to borosilicate glass.

### LINKED ISSUE #15942: MCR Forms in completely wrong shape
### Your GTNH Discord Username

elak93#1348

### Your Pack Version

2.5.1

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

In my long weekend grind, I built a few MCR's for my NAQ line, and managed to build 3 MCRS incorrectly without realising it. 

### The Reality

Rhodium-plated and LUV energy hatch MCR will form without correct glass number and without correct placement. No issues running and happy to wall share. This happily wall shares, but will not form with luv tectech hatches or zpm hatches (I have not tested more)

### Your Proposal

I assume this is a bug.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by AbdielKavash**
This PR aims to fix two interrelated bugs in structure checks:

---

First, tier of glass calculated by `BorosilicateGlass.ofBoroGlass` was in some cases calculated wrong. Specifically, the `getTier` method used to return tier -1 for any block which was not a valid glass. In cases where *none* of the blocks which were supposed to be glass were valid blocks, this value would propagate through the entire structure check, and end up with a "correctly" formed multiblock which thinks it has glass of tier -1.

In practice this means that you can replace pieces of the structure which should have been glass with [any block whatsoever](https://i.imgur.com/8zOYKnd.png), and if the check never finds any valid borosilicate glass, it will pass successfully.

---

The second issue concerns specifically the Mega Chemical Reactor, Mega Electric Blast Furnace, and Mega Oil Cracker. These three multiblocks use the tier of glass to limit the tier of energy hatches. However, this check previously only checked "exotic" energy hatches (lasers, multiamp, etc.) Regular energy hatches were ignored. This means that you could build, for example, an MCR with HV glass, and use an IV energy hatch on it.

I don't know whether this is actually intended; to me it seems like a bug, especially since no documentation (tooltips, QB) makes any mention of it. But it seems to have been the case since at least July of last year (https://github.com/GTNewHorizons/bartworks/commit/d17d3b8ebcaf7eccd7b8f3036f5161bf190690d6).

---

How are these two problems connected? Well, a multiblock could form without valid borosilicate glass blocks, and report its glass tier as -1. At the same time, as long as you use a regular energy hatch, the glass tier did not limit the tier of the energy hatch. This means that the multiblock could not only form, but also run, with a completely nonsensical construction: see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15942. (The TNT EBF I linked a picture of above was also functional.)

---

This PR fixes both problems: structure check now fails instantly if an invalid block is detected, and the tier of all energy hatches is limited by the glass type used. Tested in 2.6.0-beta-2, including with alternate types of glass (alfglass).

### CODE REVIEW

File: src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaBlastFurnace.java [hunk 1]
```diff
@@ -373,6 +373,11 @@ public boolean checkMachine(IGregTechTileEntity iGregTechTileEntity, ItemStack i
                     return false;
                 }
             }
+            for (GT_MetaTileEntity_Hatch hatch : this.mEnergyHatches) {
```
Comment (Caedis) [inline src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaBlastFurnace.java]: Mostly a micro optimization, but because this is a part of the structure checks, can this be changed to C style for loops (not enhanced for loops) to avoid any additional allocations. Same for the other 2 in this PR.

**Review by Caedis — CHANGES_REQUESTED** [review]

File: src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaBlastFurnace.java (hunk 1 above)
Comment (Caedis) [reply src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaBlastFurnace.java]: Lot of multis and this starts to add up

Comment (AbdielKavash) [reply src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaBlastFurnace.java]: I have replaced the loops in the three multis this affects. But as I mentioned in discord, this feels like a spit in an ocean, given that the enhanced for is used nearly everywhere else, including in places called more often than structure checks.

**Review by Caedis — APPROVED** [review]
